---
# The name of the plugin; official plugins always start "jellyfin-plugin-"
name: "jellyfin-plugin-gotify"

# The GUID of the plugin, found in Plugin.cs
guid: "e29621a5-fa9e-4330-982e-ef6e54c0cad2"

# The version of the plugin, starting at 1. Note that the AssemblyVersion
# and FileVersion flags in the `.csproj` file must have two additional
# fiels, e.g. 1.0.0 to be built correctly.
version: "5" # Please increment with each pull request

# The supported Jellyfin version, usually the earliest binary-compatible
# version. Based on the Jellyfin components from NuGet.
jellyfin_version: "10.4.0" # The earliest binary-compatible version

# The owner name of the plugin, "jellyfin" for official plugins. Change
# to your own name if you wish to remain a 3rd-party plugin.
owner: "crobibero"

# The nicely-formatted name of the plugin
nicename: "Gotify"

# A short description of the plugin
description: "Sends notifications to your Gotify server"

# A longer and more detailed description of the plugin; use multiple
# lines as required for readability.
overview: >
    You must have a Gotify server to use this plugin!

# The plugin category, in a general sense. These fields are dynamic.
category: "Notifications"

# A list of built artifacts to be bundled into the ZIP for installation.
# Include the main output file, as well as any dependency `.dll`s that
# might be required for the plugin to run.
artifacts:
  - "Jellyfin.Plugin.Gotify.dll"

# Build information values for the build infrastructure; these should
# not need to be changed usually.
build_type: "dotnet"
dotnet_configuration: "Release"
dotnet_framework: "netstandard2.0"
